name: Update GitHub Stats
on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정에 실행
  workflow_dispatch:  # 수동 실행 가능
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Fetch GitHub Stats
        run: curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=Junyoung-Dev&show_icons=true&theme=tokyonight&count_private=true&token=${{ secrets.PAT_GITHUB_STATS }}"
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stats.svg
          git commit -m "Update GitHub Stats"
          git push

