name: Update GitHub Stats
on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정 실행
  workflow_dispatch:  # 수동 실행 가능

permissions: 
  contents: write  # ✅ 저장소에 푸시할 권한 부여

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ 기본 GitHub Actions 인증 비활성화 (토큰 사용)

      - name: Fetch GitHub Stats
        run: curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=Junyoung-Dev&show_icons=true&theme=tokyonight&count_private=true&token=${{ secrets.PAT_GITHUB_STATS }}"

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_STATS }}  # ✅ GitHub Token 사용
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg
          git commit -m "Update GitHub Stats"
          git push https://x-access-token:${{ secrets.PAT_GITHUB_STATS }}@github.com/${{ github.repository }}.git HEAD:main

